spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/feiyangbeyond/study-spring-cloud-netflix
          search-paths: config-repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: ${user.name}-${spring.application.name}:${random.int}
    prefer-ip-address: true
server:
  port: 8888