spring:
  application:
    name: config-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: ${user.name}-${spring.application.name}:${random.int}
    prefer-ip-address: true
server:
  port: 8889